- name: Join Object to Active Directory Domain
  microsoft.ad.membership:
    hostname: "{{ hostname }}"
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "black-team@{{ domain }}"
    domain_admin_password: "{{ black_team_password }}"
    state: domain
  register: result_domain

- name: Reboot Post Domain Join if Required
  ansible.windows.win_reboot:
  when: result_domain.reboot_required