---
- name: Reset recovery user
  hosts: linux
  become: true
  vars:
    user_password: "1qazxsw23edc"
  tasks:
    - name: Create users accounts
      ansible.builtin.user:
        name: recovery
        shell: "{{ shell_override | default('/bin/sh') }}"
        password: "{{ user_password | password_hash('sha256') }}"
        uid: 2000
        append: true

    - name: Allow user has passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%recovery"
        line: "recovery ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
