services:
  grafana:
    image: grafana/grafana-oss
    restart: always
    volumes:
      - ./grafana-provisioning-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml
      - ./grafana-provisioning-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
    ports:
      - 9000:3000
    depends_on:
      - "db"
      - "load-balancer"
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.chefops.tech`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=websecure"

  minio:
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir /data/loki /data/tempo && minio server --quiet /data --console-address ':9005'"]
    environment:
      - MINIO_ROOT_USER=storageuser
      - MINIO_ROOT_PASSWORD=storagepassword
    restart: always
    volumes:
      - minio-data:/data
    ports:
      - 9001:9000
      - 9005:9005

  db:
    container_name: grafana_db
    image: postgres:15-alpine
    environment:
      POSTGRES_DATABASE: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d grafana -U grafana"]
      timeout: 10s
      retries: 10
    restart: always
    ports:
      - 5432:5432

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
    ports:
      - 9090:9090

  load-balancer:
    image: nginx:mainline-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/fullchain.crt:/etc/ssl/cert.pem
      - ./ssl/private.key:/etc/ssl/key.pem
    ports:
      - 9008-9009:9008-9009
    healthcheck:
       test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
       interval: 1m30s
       timeout: 30s
       retries: 5
       start_period: 30s
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
      - "loki-1"
      - "loki-2"
      - "loki-3"

  traefik:
   image: traefik:3
   restart: always
   volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
      - "./traefik-ssl.yaml:/etc/traefik/traefik-ssl.yaml"
      - "./ssl:/etc/ssl"
   ports:
      - "443:443"
      - "8080:8080"
   extra_hosts:
      - "host.docker.internal:host-gateway"
   labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=(Host(`traefik.chefops.tech`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`)))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=traefik"

  nginx-healthcheck:
    restart: unless-stopped
    image: nginx/nginx-prometheus-exporter:1
    command: --nginx.scrape-uri=http://load-balancer:9152/
    ports:
      - 9113:9113
    depends_on:
      load-balancer:
        condition: service_healthy

  mimir-1: &mimir
    image: grafana/mimir:3
    command: ["-config.file=/etc/mimir.yaml"]
    restart: always
    hostname: mimir-1
    volumes:
      - ./mimir.yaml:/etc/mimir.yaml
      - mimir-1-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mimir.rule=Host(`mimir.chefops.tech`)"
      - "traefik.http.services.mimir.loadbalancer.server.port=8080"
      - "traefik.http.routers.mimir.entrypoints=websecure"
      - "traefik.http.services.mimir.loadbalancer.healthcheck.path=/ready"
    depends_on:
      minio:
          condition: service_started
      memcached:
          condition: service_healthy

  mimir-2:
    <<: *mimir
    hostname: mimir-2
    volumes:
      - ./mimir.yaml:/etc/mimir.yaml
      - mimir-2-data:/data

  mimir-3:
    <<: *mimir
    hostname: mimir-3
    volumes:
      - ./mimir.yaml:/etc/mimir.yaml
      - mimir-3-data:/data

  loki-1: &loki
    image: grafana/loki:3
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    hostname: loki-1
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - "loki-1-data:/loki"
    depends_on:
      memcached:
          condition: service_healthy
      minio:
          condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.chefops.tech`)"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.services.loki.loadbalancer.healthcheck.path=/ready"
      - "traefik.http.routers.loki.service=loki"

  loki-2:
    <<: *loki
    hostname: loki-2
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - "loki-2-data:/loki"


  loki-3:
    <<: *loki
    hostname: loki-3
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - "loki-3-data:/loki"

  memcached:
    image: memcached:1-alpine
    restart: always
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "11211"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 11211:11211

volumes:
  certs:
  mimir-1-data:
  mimir-2-data:
  mimir-3-data:
  loki-1-data:
  loki-2-data:
  loki-3-data:
  grafana-storage:
  postgres-data:
  minio-data:
