apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9008/prometheus
    version: 1
    editable: false
    jsonData:
      httpMethod: "POST"
      prometheusType: "Mimir"
      prometheusVersion: "2.9.1"
    secureJsonData:
    isDefault: true
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://load-balancer:9009
    version: 1
    editable: false
