---
- name: Normalize DNS forwarder list
  ansible.builtin.set_fact:
    dns_forwarder_list: >-
      {{
        dns_forwarders
        if (dns_forwarders is iterable and dns_forwarders is not string)
        else [dns_forwarders]
      }}
  when: dns_forwarders is defined

- name: Set DNS zone forwarder
  ansible.windows.win_powershell:
    script: |
      Set-DnsServerForwarder -IPAddress {{ dns_forwarder_list | join(',') }} -PassThru
  when:
    - dns_forwarder_list is defined
    - dns_forwarder_list | length > 0
