kind: role
version: v7
metadata:
  name: support
  description: Support role with access to kiosk systems
spec:
  allow:
    logins:
      - support
    node_labels:
      system: kiosk
---
kind: role
version: v7
metadata:
  name: support-linux
  description: Support client linux systems
---
kind: role
version: v7
metadata:
  name: support-windows
  description: Support client Windows systems
