{
 "title": "Teleport",
 "description": "A simple dashboard showing statistics for Teleport.\r\nRequires Teleport Metrics to be enabled and scraped by your Prometheus instance.",
 "tags": [
  "security",
  "teleport"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Teleport Component Versions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(app_kubernetes_io_component, version) (teleport_build_info)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Teleport Sessions",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(teleport_active_connections)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(ingress_service) (teleport_active_connections)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected Resources",
   "type": "stat",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(teleport_connected_resources)",
     "legendFormat": "Total"
    },
    { "expr": "teleport_connected_resources", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Connection Rate (per Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(ingress_service) (rate(teleport_accepted_connections_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Rate (Total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (rate(teleport_accepted_connections_total[$__rate_interval]))",
     "legendFormat": "{{ingress_service}}"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Backend IOPS",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(teleport_backend_writes_total[$__rate_interval]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(rate(teleport_backend_reads_total[$__rate_interval]))",
     "legendFormat": "Reads"
    }
   ]
  }
 ]
}