{
 "title": "Falco Alerts",
 "tags": [
  "security",
  "falco"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Alert Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"falco-alerts\"} | json [1h])) by (rule)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 24, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"falco-alerts\"}"
    }
   ]
  },
  {
   "title": "Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"falco-alerts\"} | json [1h])) by (priority)"
    }
   ]
  },
  {
   "title": "Systems",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"falco-alerts\"} | json [1h])) by (instance)"
    }
   ]
  }
 ]
}