---
- name: Reset Ansible user
  hosts: linux
  become: true
  vars:
    user_password: "1qazxsw23edc"
  tasks:
    - name: Create users accounts
      ansible.builtin.user:
        name: ansible
        shell: "{{ shell_override | default('/bin/sh') }}"
        password: "{{ user_password | password_hash('sha256') }}"
        uid: 2000
        append: true
      tags:
        - ansible

    - name: Ensure group "ansible" exists
      ansible.builtin.group:
        name: ansible
        state: present
      tags:
        - ansible

    - name: Make sure ansible user has self group
      ansible.builtin.user:
        name: ansible
        groups: ansible
        append: true
      tags:
        - ansible

    - name: Allow user has passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%ansible"
        line: "%ansible ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
      tags:
        - ansible
