---
- name: Configure Kiosks
  hosts: kiosks
  become: true
  vars:
    team_number: "{{ hostvars[inventory_hostname]['team'] }}"
  tasks:
    - name: Copy full chain certificates
      ansible.builtin.copy:
        src: "../../../../documents/blue_team/regionals/ock/team_{{ team_number }}/certificates/{{ item }}"
        dest: /etc/nginx/{{ item }}
        mode: "0400"
        owner: root
        group: root
      with_items:
        - fullchain.crt
        - private.key
      tags:
        - certificates

    - name: Update Nginx Config with Team Specific Hostname
      ansible.builtin.replace:
        path: "/etc/nginx/sites-enabled/site.conf"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - {
            regexp: 'kiosk\.oceancrests\.kitchen',
            replace: "{{ inventory_hostname_short }}.{{ team_number }}.oceancrests.kitchen",
          }

    - name: Update Teleport server name
      ansible.builtin.replace:
        path: /etc/teleport.yaml
        regexp: "nodename: kiosk$"
        replace: "nodename: kiosk-{{ id }}"
      tags:
        - teleport

    - name: Start Kiosk Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
