kind: role
version: v7
metadata:
  name: wordpress-admin
  description: Wordpress administrator
spec:
  options:
    max_session_ttl: 8h
  allow:
    app_labels:
      app: wordpress
    logins:
      - admin
      - '{{internal.logins}}'
    node_labels:
      service: wordpress
