---
- name: Install WordPress
  hosts: packer
  user: user
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
    wordpress_action: install
    users_data: "{{ lookup('file', '../../../../documents/employees/employees.yaml') | from_yaml }}"
    former_users_data: "{{ lookup('file', '../../../../documents/employees/former_employees.yaml') | from_yaml }}"
  roles:
    - wordpress_install
  tasks:
    - name: Weaken SSH
      ansible.builtin.include_tasks:
        file: "../../../shared/weaken_ssh/main.yaml"
      tags:
        - ssh

    - name: Set Ansible user
      ansible.builtin.include_tasks:
        file: "../../shared/semaphore_ansible/main.yaml"
      tags:
        - ansible

    - name: Setup Alloy
      ansible.builtin.include_tasks:
        file: "../../../shared/alloy/main.yaml"
      vars:
        mode: "pre"
        include_docker: false
        extra_config: |
          prometheus.scrape "falco" {
            targets = [
              {
                __address__ = "127.0.0.1:8765",
                instance    = constants.hostname,
                job         = "falco",
              },
            ]
            forward_to      = [prometheus.remote_write.remote.receiver]
            scrape_interval = "10m"
          }

          loki.source.file "falco_alerts" {
            targets = [
              {
                __path__ = "/var/log/falco_alerts.log",
                job      = "falco-alerts",
                instance = constants.hostname,
              },
            ]
            forward_to = [loki.process.falco_alerts.receiver]
          }

          loki.process "falco_alerts" {
            forward_to = [loki.write.remote.receiver]

            stage.json {
              expressions = {
                priority  = "priority",
                rule      = "rule",
                source    = "source",
                hostname  = "hostname",
                output    = "output",
              }
            }

            stage.labels {
              values = {
                priority = "",
                rule     = "",
                source   = "",
              }
            }
          }
      tags:
        - alloy

    - name: Install Teleport client
      ansible.builtin.include_tasks:
        file: "../../../shared/teleport_client/main.yaml"
      vars:
        teleport_node_name: wordpress
        teleport_join_token: 47ob9wt6u0h8ucb9f2rdWPEngine
        teleport_node_label:
          service: wordpress
        teleport_major_version_override: v16
        teleport_app_service_enabled: "no"
      tags:
        - teleport

    # The main task does this but need to have custom DB options.
    - name: Configure Teleport.
      ansible.builtin.template:
        src: templates/teleport.yaml.j2
        dest: /etc/teleport.yaml
        validate: '/usr/local/bin/teleport configure --test %s'
        mode: '0644'
      vars:
        teleport_join_token: 47ob9wt6u0h8ucb9f2rdWPEngine
      tags:
        - teleport

    # https://goteleport.com/docs/enroll-resources/database-access/enrollment/self-hosted/mysql-self-hosted/
    - name: MariaDB Teleport access
      ansible.builtin.include_tasks:
        file: "tasks/mariadb_teleport.yaml"
      tags:
        - mariadb
        - teleport

    - name: MariaDB black-team user
      ansible.builtin.include_tasks:
        file: "tasks/mariadb_black_team.yaml"
      tags:
        - black-team
        - mariadb

    - name: Install Falco
      ansible.builtin.include_tasks:
        file: "../../shared/falco_client/main.yaml"
      vars:
        falco_version: "0.42.1"
      tags:
        - falco

    - name: Install EIC
      ansible.builtin.include_tasks:
        file: "../../../shared/ec2_instance_connect/main.yaml"
      tags:
        - eic

    - name: Setup black team task
      ansible.builtin.include_tasks:
        file: "../../../shared/black_team/main.yaml"
      tags:
        - black-team

    - name: AWS SSM Agent
      block:
        - name: AWS SSM Agent | Install
          ansible.builtin.command:
            cmd: snap install amazon-ssm-agent --classic
          tags:
            - ssm

        - name: AWS SSM Agent | Start and enable
          ansible.builtin.service:
            name: snap.amazon-ssm-agent.amazon-ssm-agent
            state: started
            enabled: true
          tags:
            - ssm

    - name: Create Linux user groups
      ansible.builtin.group:
        name: "{{ item | regex_replace(' ', '-') | lower }}"
        state: present
      with_items:
        - engineering
        - sales
        - security
      tags:
        - users

    - name: Allow engineering sudo access
      community.general.sudoers:
        name: internal-engineering
        state: present
        group: engineering
        nopassword: true
        commands: ALL
      tags:
        - users

    - name: Create Security Specialist User
      ansible.builtin.user:
        name: "{{ item.username | regex_replace(' ', '.') | lower }}"
        password: "{{ item.password | password_hash('sha512') }}"
        append: true
        groups: security,users
        shell: "/bin/bash"
        generate_ssh_key: true
        state: present
      when: item.department == "Security" and item.position == "Security Specialist"
      with_items: "{{ users_data.users }}"
      tags:
        - users

    - name: Create System Admin Users
      ansible.builtin.user:
        name: "{{ item.username | regex_replace(' ', '.') | lower }}"
        password: "{{ item.password | password_hash('sha512') }}"
        append: true
        groups: engineering,users
        shell: "/bin/bash"
        state: present
      when: item.department == "Engineering" and item.position == "System Admin"
      with_items: "{{ users_data.users }}"
      tags:
        - users

    - name: Create CTO user
      ansible.builtin.user:
        name: "{{ item.username | regex_replace(' ', '.') | lower }}"
        password: "{{ item.password | password_hash('sha512') }}"
        append: true
        groups: engineering,users
        shell: "/bin/bash"
        state: present
      when: item.position == "CTO"
      with_items: "{{ users_data.users }}"
      tags:
        - users

    - name: Create sales users
      ansible.builtin.user:
        name: "{{ item.username | regex_replace(' ', '.') | lower }}"
        password: "{{ item.password | password_hash('sha512') }}"
        append: true
        groups: sales,users
        shell: "/bin/sh"
        password_expire_min: 2
        state: present
      when: item.department == "Sales"
      with_items: "{{ users_data.users }}"
      tags:
        - users

    - name: Create CEO user
      ansible.builtin.user:
        name: "{{ item.username | regex_replace(' ', '.') | lower }}"
        password: "{{ item.password | password_hash('sha512') }}"
        append: true
        groups: sales,engineering,users
        shell: "/bin/bash"
        generate_ssh_key: true
        comment: "Ordered access for an update to the website"
        state: present
      when: item.position == "CEO"
      with_items: "{{ users_data.users }}"
      tags:
        - users

    - name: Create Former System Admin Users
      ansible.builtin.user:
        name: "{{ item.username | regex_replace(' ', '.') | lower }}"
        password: "{{ item.password | password_hash('sha512') }}"
        append: true
        groups: engineering,users
        shell: "/bin/bash"
        generate_ssh_key: true
        state: present
      when: item.department == "Engineering" and item.position == "System Admin"
      with_items: "{{ former_users_data.users }}"
      tags:
        - users

    - name: Tricks
      ansible.builtin.include_tasks:
        file: "tasks/tricks.yaml"
      tags:
        - tricks
