---
- name: Set Windows Client DNS Servers
  ansible.windows.win_dns_client:
    adapter_names: "*"
    dns_servers: "{{ dns_servers }}"
  when:
    - dns_servers is defined
    - ansible_facts["windows_domain_role"] != 'Primary domain controller'
