---
- name: Make sure Falco plugins directory exists
  ansible.builtin.file:
    dest: /usr/share/falco/plugins
    state: directory
    mode: "0755"
  tags:
    - falco

# Build on arm64 linux server, was not able to get it working locally
#
# apt install -y make gcc git
# wget https://go.dev/dl/go1.22.0.linux-arm64.tar.gz
# tar -C /usr/local -xzf go1.22.0.linux-arm64.tar.gz
# export PATH=$PATH:/usr/local/go/bin
# git clone https://github.com/takaosgb3/falco-plugin-nginx.git
# cd falco-plugin-nginx
# make build
#
# Copy the file back to the host

# Cannot use the default plugins since it only is for amd64
- name: Copy Falco Nginx plugin
  ansible.builtin.copy:
    src: files/libfalco-nginx-plugin.so
    dest: /usr/share/falco/plugins/libfalco-nginx-plugin.so
    owner: root
    group: root
    mode: "0644"
  tags:
    - falco

- name: Make sure Falco rules directory exists
  ansible.builtin.file:
    dest: /etc/falco/rules.d
    state: directory
    mode: "0755"
  tags:
    - falco

- name: Download Falco Nginx rules
  ansible.builtin.get_url:
    url: "https://github.com/takaosgb3/falco-plugin-nginx/releases/download/v1.7.0/nginx_rules.yaml"
    dest: /etc/falco/rules.d/nginx.yaml
    owner: root
    group: root
    mode: "0644"
  tags:
    - falco

- name: Copy Falco Nginx config
  ansible.builtin.copy:
    src: files/falco_nginx.yaml
    dest: /etc/falco/config.d/nginx.yaml
    mode: "0644"
    backup: false
  tags:
    - falco
