---
- name: restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true

- name: restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true

- name: mark user created
  ansible.builtin.file:
    path: /tmp/wp_user_created
    state: touch
  become: true
