---
- name: Create black-team user
  ansible.windows.win_user:
    name: "{{ black_team_user | default('black-team') }}"
    password: "{{ black_team_password }}"
    description: DO NOT TOUCH THIS ACCOUNT
    state: present
    groups:
      - Administrators

- name: Create ssm-user user
  ansible.windows.win_user:
    name: "ssm-user"
    password: "{{ black_team_password }}"
    description: DO NOT TOUCH THIS ACCOUNT
    state: present
    groups:
      - Administrators