---
- name: Download OSPOS release
  ansible.windows.win_get_url:
    url: "{{ ospos_url }}"
    dest: C:\xampp\htdocs\ospos.zip

- name: Unzip OSPOS
  ansible.builtin.win_unzip:
    src: C:\xampp\htdocs\ospos.zip
    dest: C:\xampp\htdocs\ospos
    creates: C:\xampp\htdocs\ospos\README.md

- name: Template .env file for OSPOS
  ansible.builtin.win_template:
    src: templates/.env.j2
    dest: C:\xampp\htdocs\ospos\.env
